language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
script:
  - pip install pytest . && pytest
matrix:
  allow_failures:
    - python: "3.7"
    - python: "nightly"
